// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// crossprodRcpp
Rcpp::List crossprodRcpp(Eigen::Map<Eigen::MatrixXd> A);
RcppExport SEXP kernDeepStackNet_crossprodRcpp(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(crossprodRcpp(A));
    return rcpp_result_gen;
END_RCPP
}
// getEigenValuesRcpp
Eigen::VectorXd getEigenValuesRcpp(Eigen::Map<Eigen::MatrixXd> M);
RcppExport SEXP kernDeepStackNet_getEigenValuesRcpp(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(getEigenValuesRcpp(M));
    return rcpp_result_gen;
END_RCPP
}
