// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// crossprodRcpp
Rcpp::List crossprodRcpp(Eigen::Map<Eigen::MatrixXd> A);
RcppExport SEXP kernDeepStackNet_crossprodRcpp(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type A(ASEXP);
    __result = Rcpp::wrap(crossprodRcpp(A));
    return __result;
END_RCPP
}
// getEigenValuesRcpp
Eigen::VectorXd getEigenValuesRcpp(Eigen::Map<Eigen::MatrixXd> M);
RcppExport SEXP kernDeepStackNet_getEigenValuesRcpp(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type M(MSEXP);
    __result = Rcpp::wrap(getEigenValuesRcpp(M));
    return __result;
END_RCPP
}
